version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY_HEADERS: "xforwarded"
      # Aggiungiamo questa riga per dire a Keycloak di usare un file per i dati
      KC_DB: dev-file 
    ports:
      - "8080:8080"
    volumes:
      # Questa riga salva i dati di Keycloak in una cartella locale del tuo Codespace
      - ./keycloak_data:/opt/keycloak/data
    command:
      - start-dev